service: aws-cron
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 256
  stage: dev
  timeout: 30 # repository wide Lambda timeout
  environment: # repository wide Lambda env variables
    NODE_ENV: production

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk'] # Exclude AWS SDK as it is already available in the AWS environment
    target: 'node20'    # Node.js version must match your runtime
    define: {'require.resolve': 'undefined'}
    platform: 'node'
    concurrency: 10

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: any
          cors: true
